find_package(Threads REQUIRED)
add_definitions(-DHAVE_PTHREAD -DOPENSOURCE_PROTOBUF_CPP_BOOTSTRAP)
set(protobuf_source_dir "ext/protobuf")

add_library(libprotobuf STATIC
    ${protobuf_source_dir}/src/google/protobuf/arena.cc
    ${protobuf_source_dir}/src/google/protobuf/arenastring.cc
    ${protobuf_source_dir}/src/google/protobuf/extension_set.cc
    ${protobuf_source_dir}/src/google/protobuf/generated_message_table_driven_lite.cc
    ${protobuf_source_dir}/src/google/protobuf/generated_message_util.cc
    ${protobuf_source_dir}/src/google/protobuf/implicit_weak_message.cc
    ${protobuf_source_dir}/src/google/protobuf/io/coded_stream.cc
    ${protobuf_source_dir}/src/google/protobuf/io/zero_copy_stream.cc
    ${protobuf_source_dir}/src/google/protobuf/io/zero_copy_stream_impl_lite.cc
    ${protobuf_source_dir}/src/google/protobuf/message_lite.cc
    ${protobuf_source_dir}/src/google/protobuf/repeated_field.cc
    ${protobuf_source_dir}/src/google/protobuf/stubs/bytestream.cc
    ${protobuf_source_dir}/src/google/protobuf/stubs/common.cc
    ${protobuf_source_dir}/src/google/protobuf/stubs/int128.cc
    ${protobuf_source_dir}/src/google/protobuf/stubs/io_win32.cc
    ${protobuf_source_dir}/src/google/protobuf/stubs/status.cc
    ${protobuf_source_dir}/src/google/protobuf/stubs/statusor.cc
    ${protobuf_source_dir}/src/google/protobuf/stubs/stringpiece.cc
    ${protobuf_source_dir}/src/google/protobuf/stubs/stringprintf.cc
    ${protobuf_source_dir}/src/google/protobuf/stubs/structurally_valid.cc
    ${protobuf_source_dir}/src/google/protobuf/stubs/strutil.cc
    ${protobuf_source_dir}/src/google/protobuf/stubs/time.cc
    ${protobuf_source_dir}/src/google/protobuf/wire_format_lite.cc

    ${protobuf_source_dir}/src/google/protobuf/arena.h
    ${protobuf_source_dir}/src/google/protobuf/arenastring.h
    ${protobuf_source_dir}/src/google/protobuf/extension_set.h
    ${protobuf_source_dir}/src/google/protobuf/generated_message_util.h
    ${protobuf_source_dir}/src/google/protobuf/implicit_weak_message.h
    ${protobuf_source_dir}/src/google/protobuf/io/coded_stream.h
    ${protobuf_source_dir}/src/google/protobuf/io/zero_copy_stream.h
    ${protobuf_source_dir}/src/google/protobuf/io/zero_copy_stream_impl_lite.h
    ${protobuf_source_dir}/src/google/protobuf/message_lite.h
    ${protobuf_source_dir}/src/google/protobuf/repeated_field.h
    ${protobuf_source_dir}/src/google/protobuf/stubs/bytestream.h
    ${protobuf_source_dir}/src/google/protobuf/stubs/common.h
    ${protobuf_source_dir}/src/google/protobuf/stubs/int128.h
    ${protobuf_source_dir}/src/google/protobuf/stubs/once.h
    ${protobuf_source_dir}/src/google/protobuf/stubs/status.h
    ${protobuf_source_dir}/src/google/protobuf/stubs/statusor.h
    ${protobuf_source_dir}/src/google/protobuf/stubs/stringpiece.h
    ${protobuf_source_dir}/src/google/protobuf/stubs/stringprintf.h
    ${protobuf_source_dir}/src/google/protobuf/stubs/strutil.h
    ${protobuf_source_dir}/src/google/protobuf/stubs/time.h
    ${protobuf_source_dir}/src/google/protobuf/wire_format_lite.h

    ${protobuf_source_dir}/src/google/protobuf/any.cc
    ${protobuf_source_dir}/src/google/protobuf/any.pb.cc
    ${protobuf_source_dir}/src/google/protobuf/api.pb.cc
    ${protobuf_source_dir}/src/google/protobuf/compiler/importer.cc
    ${protobuf_source_dir}/src/google/protobuf/compiler/parser.cc
    ${protobuf_source_dir}/src/google/protobuf/descriptor.cc
    ${protobuf_source_dir}/src/google/protobuf/descriptor.pb.cc
    ${protobuf_source_dir}/src/google/protobuf/descriptor_database.cc
    ${protobuf_source_dir}/src/google/protobuf/duration.pb.cc
    ${protobuf_source_dir}/src/google/protobuf/dynamic_message.cc
    ${protobuf_source_dir}/src/google/protobuf/empty.pb.cc
    ${protobuf_source_dir}/src/google/protobuf/extension_set_heavy.cc
    ${protobuf_source_dir}/src/google/protobuf/field_mask.pb.cc
    ${protobuf_source_dir}/src/google/protobuf/generated_message_reflection.cc
    ${protobuf_source_dir}/src/google/protobuf/generated_message_table_driven.cc
    ${protobuf_source_dir}/src/google/protobuf/io/gzip_stream.cc
    ${protobuf_source_dir}/src/google/protobuf/io/printer.cc
    ${protobuf_source_dir}/src/google/protobuf/io/strtod.cc
    ${protobuf_source_dir}/src/google/protobuf/io/tokenizer.cc
    ${protobuf_source_dir}/src/google/protobuf/io/zero_copy_stream_impl.cc
    ${protobuf_source_dir}/src/google/protobuf/map_field.cc
    ${protobuf_source_dir}/src/google/protobuf/message.cc
    ${protobuf_source_dir}/src/google/protobuf/reflection_ops.cc
    ${protobuf_source_dir}/src/google/protobuf/service.cc
    ${protobuf_source_dir}/src/google/protobuf/source_context.pb.cc
    ${protobuf_source_dir}/src/google/protobuf/struct.pb.cc
    ${protobuf_source_dir}/src/google/protobuf/stubs/mathlimits.cc
    ${protobuf_source_dir}/src/google/protobuf/stubs/substitute.cc
    ${protobuf_source_dir}/src/google/protobuf/text_format.cc
    ${protobuf_source_dir}/src/google/protobuf/timestamp.pb.cc
    ${protobuf_source_dir}/src/google/protobuf/type.pb.cc
    ${protobuf_source_dir}/src/google/protobuf/unknown_field_set.cc
    ${protobuf_source_dir}/src/google/protobuf/util/delimited_message_util.cc
    ${protobuf_source_dir}/src/google/protobuf/util/field_comparator.cc
    ${protobuf_source_dir}/src/google/protobuf/util/field_mask_util.cc
    ${protobuf_source_dir}/src/google/protobuf/util/internal/datapiece.cc
    ${protobuf_source_dir}/src/google/protobuf/util/internal/default_value_objectwriter.cc
    ${protobuf_source_dir}/src/google/protobuf/util/internal/error_listener.cc
    ${protobuf_source_dir}/src/google/protobuf/util/internal/field_mask_utility.cc
    ${protobuf_source_dir}/src/google/protobuf/util/internal/json_escaping.cc
    ${protobuf_source_dir}/src/google/protobuf/util/internal/json_objectwriter.cc
    ${protobuf_source_dir}/src/google/protobuf/util/internal/json_stream_parser.cc
    ${protobuf_source_dir}/src/google/protobuf/util/internal/object_writer.cc
    ${protobuf_source_dir}/src/google/protobuf/util/internal/proto_writer.cc
    ${protobuf_source_dir}/src/google/protobuf/util/internal/protostream_objectsource.cc
    ${protobuf_source_dir}/src/google/protobuf/util/internal/protostream_objectwriter.cc
    ${protobuf_source_dir}/src/google/protobuf/util/internal/type_info.cc
    ${protobuf_source_dir}/src/google/protobuf/util/internal/type_info_test_helper.cc
    ${protobuf_source_dir}/src/google/protobuf/util/internal/utility.cc
    ${protobuf_source_dir}/src/google/protobuf/util/json_util.cc
    ${protobuf_source_dir}/src/google/protobuf/util/message_differencer.cc
    ${protobuf_source_dir}/src/google/protobuf/util/time_util.cc
    ${protobuf_source_dir}/src/google/protobuf/util/type_resolver_util.cc
    ${protobuf_source_dir}/src/google/protobuf/wire_format.cc
    ${protobuf_source_dir}/src/google/protobuf/wrappers.pb.cc

    ${protobuf_source_dir}/src/google/protobuf/any.h
    ${protobuf_source_dir}/src/google/protobuf/any.pb.h
    ${protobuf_source_dir}/src/google/protobuf/api.pb.h
    ${protobuf_source_dir}/src/google/protobuf/compiler/importer.h
    ${protobuf_source_dir}/src/google/protobuf/compiler/parser.h
    ${protobuf_source_dir}/src/google/protobuf/descriptor.h
    ${protobuf_source_dir}/src/google/protobuf/descriptor.pb.h
    ${protobuf_source_dir}/src/google/protobuf/descriptor_database.h
    ${protobuf_source_dir}/src/google/protobuf/duration.pb.h
    ${protobuf_source_dir}/src/google/protobuf/dynamic_message.h
    ${protobuf_source_dir}/src/google/protobuf/empty.pb.h
    ${protobuf_source_dir}/src/google/protobuf/field_mask.pb.h
    ${protobuf_source_dir}/src/google/protobuf/generated_message_reflection.h
    ${protobuf_source_dir}/src/google/protobuf/io/gzip_stream.h
    ${protobuf_source_dir}/src/google/protobuf/io/printer.h
    ${protobuf_source_dir}/src/google/protobuf/io/strtod.h
    ${protobuf_source_dir}/src/google/protobuf/io/tokenizer.h
    ${protobuf_source_dir}/src/google/protobuf/io/zero_copy_stream_impl.h
    ${protobuf_source_dir}/src/google/protobuf/map_field.h
    ${protobuf_source_dir}/src/google/protobuf/message.h
    ${protobuf_source_dir}/src/google/protobuf/reflection_ops.h
    ${protobuf_source_dir}/src/google/protobuf/service.h
    ${protobuf_source_dir}/src/google/protobuf/source_context.pb.h
    ${protobuf_source_dir}/src/google/protobuf/struct.pb.h
    ${protobuf_source_dir}/src/google/protobuf/stubs/mathlimits.h
    ${protobuf_source_dir}/src/google/protobuf/stubs/substitute.h
    ${protobuf_source_dir}/src/google/protobuf/text_format.h
    ${protobuf_source_dir}/src/google/protobuf/timestamp.pb.h
    ${protobuf_source_dir}/src/google/protobuf/type.pb.h
    ${protobuf_source_dir}/src/google/protobuf/unknown_field_set.h
    ${protobuf_source_dir}/src/google/protobuf/util/delimited_message_util.h
    ${protobuf_source_dir}/src/google/protobuf/util/field_comparator.h
    ${protobuf_source_dir}/src/google/protobuf/util/field_mask_util.h
    ${protobuf_source_dir}/src/google/protobuf/util/internal/datapiece.h
    ${protobuf_source_dir}/src/google/protobuf/util/internal/default_value_objectwriter.h
    ${protobuf_source_dir}/src/google/protobuf/util/internal/error_listener.h
    ${protobuf_source_dir}/src/google/protobuf/util/internal/field_mask_utility.h
    ${protobuf_source_dir}/src/google/protobuf/util/internal/json_escaping.h
    ${protobuf_source_dir}/src/google/protobuf/util/internal/json_objectwriter.h
    ${protobuf_source_dir}/src/google/protobuf/util/internal/json_stream_parser.h
    ${protobuf_source_dir}/src/google/protobuf/util/internal/object_writer.h
    ${protobuf_source_dir}/src/google/protobuf/util/internal/proto_writer.h
    ${protobuf_source_dir}/src/google/protobuf/util/internal/protostream_objectsource.h
    ${protobuf_source_dir}/src/google/protobuf/util/internal/protostream_objectwriter.h
    ${protobuf_source_dir}/src/google/protobuf/util/internal/type_info.h
    ${protobuf_source_dir}/src/google/protobuf/util/internal/type_info_test_helper.h
    ${protobuf_source_dir}/src/google/protobuf/util/internal/utility.h
    ${protobuf_source_dir}/src/google/protobuf/util/json_util.h
    ${protobuf_source_dir}/src/google/protobuf/util/message_differencer.h
    ${protobuf_source_dir}/src/google/protobuf/util/time_util.h
    ${protobuf_source_dir}/src/google/protobuf/util/type_resolver_util.h
    ${protobuf_source_dir}/src/google/protobuf/wire_format.h
    ${protobuf_source_dir}/src/google/protobuf/wrappers.pb.h
)

target_link_libraries(libprotobuf
    ${CMAKE_THREAD_LIBS_INIT}
    ${ZLIB_LIBRARIES}
)

target_include_directories(libprotobuf
    PUBLIC ${protobuf_source_dir}/src
)


add_library(libprotoc STATIC
    ${protobuf_source_dir}/src/google/protobuf/compiler/code_generator.cc
    ${protobuf_source_dir}/src/google/protobuf/compiler/command_line_interface.cc
    ${protobuf_source_dir}/src/google/protobuf/compiler/cpp/cpp_enum.cc
    ${protobuf_source_dir}/src/google/protobuf/compiler/cpp/cpp_enum_field.cc
    ${protobuf_source_dir}/src/google/protobuf/compiler/cpp/cpp_extension.cc
    ${protobuf_source_dir}/src/google/protobuf/compiler/cpp/cpp_field.cc
    ${protobuf_source_dir}/src/google/protobuf/compiler/cpp/cpp_file.cc
    ${protobuf_source_dir}/src/google/protobuf/compiler/cpp/cpp_generator.cc
    ${protobuf_source_dir}/src/google/protobuf/compiler/cpp/cpp_helpers.cc
    ${protobuf_source_dir}/src/google/protobuf/compiler/cpp/cpp_map_field.cc
    ${protobuf_source_dir}/src/google/protobuf/compiler/cpp/cpp_message.cc
    ${protobuf_source_dir}/src/google/protobuf/compiler/cpp/cpp_message_field.cc
    ${protobuf_source_dir}/src/google/protobuf/compiler/cpp/cpp_padding_optimizer.cc
    ${protobuf_source_dir}/src/google/protobuf/compiler/cpp/cpp_primitive_field.cc
    ${protobuf_source_dir}/src/google/protobuf/compiler/cpp/cpp_service.cc
    ${protobuf_source_dir}/src/google/protobuf/compiler/cpp/cpp_string_field.cc
    ${protobuf_source_dir}/src/google/protobuf/compiler/plugin.cc
    ${protobuf_source_dir}/src/google/protobuf/compiler/plugin.pb.cc
    ${protobuf_source_dir}/src/google/protobuf/compiler/subprocess.cc
    ${protobuf_source_dir}/src/google/protobuf/compiler/zip_writer.cc

    ${protobuf_source_dir}/src/google/protobuf/compiler/cpp/cpp_enum.h
    ${protobuf_source_dir}/src/google/protobuf/compiler/cpp/cpp_enum_field.h
    ${protobuf_source_dir}/src/google/protobuf/compiler/cpp/cpp_extension.h
    ${protobuf_source_dir}/src/google/protobuf/compiler/cpp/cpp_field.h
    ${protobuf_source_dir}/src/google/protobuf/compiler/cpp/cpp_file.h
    ${protobuf_source_dir}/src/google/protobuf/compiler/cpp/cpp_helpers.h
    ${protobuf_source_dir}/src/google/protobuf/compiler/cpp/cpp_map_field.h
    ${protobuf_source_dir}/src/google/protobuf/compiler/cpp/cpp_message.h
    ${protobuf_source_dir}/src/google/protobuf/compiler/cpp/cpp_message_field.h
    ${protobuf_source_dir}/src/google/protobuf/compiler/cpp/cpp_message_layout_helper.h
    ${protobuf_source_dir}/src/google/protobuf/compiler/cpp/cpp_options.h
    ${protobuf_source_dir}/src/google/protobuf/compiler/cpp/cpp_padding_optimizer.h
    ${protobuf_source_dir}/src/google/protobuf/compiler/cpp/cpp_primitive_field.h
    ${protobuf_source_dir}/src/google/protobuf/compiler/cpp/cpp_service.h
    ${protobuf_source_dir}/src/google/protobuf/compiler/cpp/cpp_string_field.h
    ${protobuf_source_dir}/src/google/protobuf/compiler/subprocess.h
    ${protobuf_source_dir}/src/google/protobuf/compiler/zip_writer.h
)

target_link_libraries(libprotoc
    libprotobuf
)

add_executable(protoc
    ${protobuf_source_dir}/src/google/protobuf/compiler/main.cc
)

target_link_libraries(protoc
    libprotobuf
    libprotoc
)
